## 2.2 数据操作

### 2.2.1 创建Array

In [1]:
import tensorflow as tf
tf.enable_eager_execution()
import numpy as np

/usr/local/anaconda3/envs/rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/anaconda3/envs/rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/anaconda3/envs/rknn/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/anaconda3/envs/rknn/lib/python3.6/site-packages

我们先建立一个tf静态数组

In [2]:
x = tf.constant(np.arange(12), dtype='int32')
x

<tf.Tensor: id=0, shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

我们可以通过shape属性来获取tensor属性的形状

In [3]:
x.shape

TensorShape([Dimension(12)])

下面通过reshape把行向量改为(3,4), 内容不变

In [4]:
X = tf.reshape(x, (3, 4))
X

<tf.Tensor: id=3, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

接下来，我们创建一个各元素为0，形状为(2, 3, 4)的张量.

In [5]:
tf.zeros((2, 3, 4))

<tf.Tensor: id=7, shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

类似地，我们可以创建各元素为1的张量。

In [6]:
tf.ones((3, 4))

<tf.Tensor: id=11, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

我们也可以通过Python的列表（list）指定需要创建的NDArray中每个元素的值

In [7]:
Y = tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

<tf.Tensor: id=13, shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

有些情况下，我们需要随机生成NDArray中每个元素的值。下面我们创建一个形状为(3, 4)的NDArray。它的每个元素都随机采样于均值为0、标准差为1的正态分布。

In [8]:
tf.random.normal(shape=(3, 4), mean=0., stddev=1.)

<tf.Tensor: id=20, shape=(3, 4), dtype=float32, numpy=
array([[ 1.6400409 ,  0.08271278, -1.0968661 , -0.9266892 ],
       [ 0.20699595,  0.6009933 ,  0.00175444, -0.65833443],
       [ 0.63425565,  0.33364412,  0.15763462, -0.11734708]],
      dtype=float32)>

### 2.2.2 运算

按元素加法：

In [9]:
X + Y

<tf.Tensor: id=22, shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]], dtype=int32)>

按元素乘法：

In [10]:
X * Y

<tf.Tensor: id=24, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]], dtype=int32)>

按元素除法：

In [11]:
X / Y

<tf.Tensor: id=28, shape=(3, 4), dtype=float64, numpy=
array([[ 0.  ,  1.  ,  0.5 ,  1.  ],
       [ 4.  ,  2.5 ,  2.  ,  1.75],
       [ 2.  ,  3.  ,  5.  , 11.  ]])>

按元素做指数运算：

In [12]:
tf.exp(tf.cast(Y, 'float32'))

<tf.Tensor: id=31, shape=(3, 4), dtype=float32, numpy=
array([[ 7.389056 ,  2.7182817, 54.598152 , 20.085537 ],
       [ 2.7182817,  7.389056 , 20.085537 , 54.598152 ],
       [54.598152 , 20.085537 ,  7.389056 ,  2.7182817]], dtype=float32)>

除了按元素计算外，我们还可以使用dot函数(或者@)做矩阵乘法。

In [13]:
X @ tf.transpose(Y)

<tf.Tensor: id=35, shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]], dtype=int32)>

我们也可以将多个Tensor连结（concatenate）。下面分别在行上（维度0，即形状中的最左边元素）和列上（维度1，即形状中左起第二个元素）连结两个矩阵。

In [14]:
tf.concat((X, Y), axis=0), tf.concat((X, Y), axis=1)

(<tf.Tensor: id=38, shape=(6, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]], dtype=int32)>,
 <tf.Tensor: id=40, shape=(3, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]], dtype=int32)>)

使用条件判断式可以得到元素为True或False的新的Tensor

In [15]:
tf.equal(X, Y)

<tf.Tensor: id=43, shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

对Tensor中的所有元素求和得到只有一个元素的Tensor.

In [16]:
tf.reduce_sum(X)

<tf.Tensor: id=46, shape=(), dtype=int32, numpy=66>

我们可以通过numpy函数将结果变换为Python中的标量

In [17]:
tf.norm(tf.cast(X, 'float32')).numpy()

22.494444

### 2.2.3 广播机制

前面我们看到如何对两个形状相同的Tensor做按元素运算。当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算。

In [18]:
A = tf.constant(np.arange(3).reshape((3, 1)))
B = tf.constant(np.arange(2).reshape((1, 2)))
A, B

(<tf.Tensor: id=55, shape=(3, 1), dtype=int64, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: id=56, shape=(1, 2), dtype=int64, numpy=array([[0, 1]])>)

由于A和B分别是3行1列和1行2列的矩阵，如果要计算A + B，那么A中第一列的3个元素被广播（复制）到了第二列，而B中第一行的2个元素被广播（复制）到了第二行和第三行。如此，就可以对2个3行2列的矩阵按元素相加。

In [19]:
A + B

<tf.Tensor: id=59, shape=(3, 2), dtype=int64, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

### 2.2.4 索引

与numpy数组一致，在Tensor中，索引（index）代表了元素的位置。Tensor的索引从0开始逐一递增。例如，一个3行2列的矩阵的行索引分别为0、1和2，列索引分别为0和1。
在下面的例子中，我们指定了Tensor的行索引截取范围\[1:3\]。依据左闭右开指定范围的惯例，它截取了矩阵X中行索引为1和2的两行。

In [20]:
X[1:3]

<tf.Tensor: id=64, shape=(2, 4), dtype=int32, numpy=
array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

### 2.2.5 运算的内存开销

### 2.2.6 Tensor和NumPy相互变换

In [21]:
P = np.ones((2, 3))
D = tf.constant(P)
D

<tf.Tensor: id=66, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [22]:
D.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])