## 4.5. 读取和存储

### 4.5.1 读写NDArray

In [1]:
import numpy as np
import keras

Using TensorFlow backend.


In [2]:
x = np.ones(3)
np.save('x', x)

In [3]:
x2 = np.load('x.npy')
x2

array([1., 1., 1.])

In [4]:
y = np.zeros(4)
np.save('xy', [x, y])
x2, y2 = np.load('xy.npy', allow_pickle=True)
(x2, y2)

(array([1., 1., 1.]), array([0., 0., 0., 0.]))

In [5]:
mydict = {'x': x, 'y': y}
np.save('mydict', mydict)
mydict2 = np.load('mydict.npy', allow_pickle=True)
mydict2

array({'x': array([1., 1., 1.]), 'y': array([0., 0., 0., 0.])},
      dtype=object)

### 4.5.2 读写模型的参数

In [6]:
class MLP(keras.Model):
    def __init__(self, *args, **kwargs):
        super(MLP, self).__init__(*args, **kwargs)
        self._hidden = keras.layers.Dense(256, activation='relu', input_shape=(-1, 20))  # 隐藏层
        self._output = keras.layers.Dense(10)  # 输出层
        
    def call(self, inputs, mask=None):
        return self._output(self._hidden(inputs))
    

X = np.random.uniform(size=(2, 20))
net = MLP()
net.compile(optimizer='SGD')
Y = net.predict(X)
Y

array([[ 0.14410365, -0.4554479 , -0.19005285,  0.03440062, -0.20024411,
        -0.19285695, -0.40570748,  0.02103331,  0.24497485,  0.25585425],
       [ 0.05656903, -0.43712315, -0.01691777,  0.08223102, -0.21248649,
        -0.18659651, -0.20143217, -0.02510154,  0.07831832, -0.05396916]],
      dtype=float32)

In [7]:
filename = 'mlp.parms'
net.save_weights(filename)

In [8]:
net2 = MLP()
net2.load_weights(filename)

ValueError: You are trying to load a weight file containing 2 layers into a model with 0 layers.

In [ ]:
Y2 = net2.predict(X)
Y == Y2